version: "3.3"

services:
  traefik:
    image: traefik:v1.7
    restart: always
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json

  counter:
    build: .
    container_name: "counter"
    labels:
      - "traefik.backend=counter"
      - "traefik.frontend.rule=HostRegexp:{catchall:.*}"
      - "traefik.frontend.priority=1"
      - "traefik.enable=true"
      - "traefik.port=8080"